version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
    env_file:
      - .env
    networks:
      - raptor-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "1230:80"
    depends_on:
      - api
    networks:
      - raptor-network

networks:
  raptor-network:
    driver: bridge